/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as EmbedDotjsRouteImport } from './routes/embed[.]js'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppPenelitianRouteImport } from './routes/_app/penelitian'
import { Route as AppResearchRouteImport } from './routes/_app/research'
import { Route as AppTentangRouteImport } from './routes/_app/tentang'
import { Route as AppWidgetRouteImport } from './routes/_app/widget'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as AppAnggotaIndexRouteImport } from './routes/_app/anggota/index'
import { Route as AppAnggotaSlugRouteImport } from './routes/_app/anggota/$slug'
import { Route as AppBeritaIndexRouteImport } from './routes/_app/berita/index'
import { Route as AppBeritaSlugRouteImport } from './routes/_app/berita/$slug'
import { Route as AppNewsIndexRouteImport } from './routes/_app/news/index'
import { Route as AppNewsSlugRouteImport } from './routes/_app/news/$slug'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPeopleSlugRouteImport } from './routes/_app/people/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDotjsRoute = EmbedDotjsRouteImport.update({
  id: '/embed.js',
  path: '/embed.js',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPenelitianRoute = AppPenelitianRouteImport.update({
  id: '/penelitian',
  path: '/penelitian',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppTentangRoute = AppTentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => AppRoute,
} as any)
const AppWidgetRoute = AppWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AppRoute,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnggotaIndexRoute = AppAnggotaIndexRouteImport.update({
  id: '/anggota/',
  path: '/anggota/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnggotaSlugRoute = AppAnggotaSlugRouteImport.update({
  id: '/anggota/$slug',
  path: '/anggota/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBeritaIndexRoute = AppBeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => AppRoute,
} as any)
const AppBeritaSlugRoute = AppBeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsSlugRoute = AppNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleSlugRoute = AppPeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/embed': typeof EmbedRoute
  '/embed.js': typeof EmbedDotjsRoute
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/admin': typeof AppAdminRoute
  '/penelitian': typeof AppPenelitianRoute
  '/research': typeof AppResearchRoute
  '/tentang': typeof AppTentangRoute
  '/widget': typeof AppWidgetRoute
  '/api/news': typeof ApiNewsRoute
  '/anggota/$slug': typeof AppAnggotaSlugRoute
  '/berita/$slug': typeof AppBeritaSlugRoute
  '/news/$slug': typeof AppNewsSlugRoute
  '/people/$slug': typeof AppPeopleSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/anggota/': typeof AppAnggotaIndexRoute
  '/berita/': typeof AppBeritaIndexRoute
  '/news/': typeof AppNewsIndexRoute
  '/people/': typeof AppPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/embed': typeof EmbedRoute
  '/embed.js': typeof EmbedDotjsRoute
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/admin': typeof AppAdminRoute
  '/penelitian': typeof AppPenelitianRoute
  '/research': typeof AppResearchRoute
  '/tentang': typeof AppTentangRoute
  '/widget': typeof AppWidgetRoute
  '/api/news': typeof ApiNewsRoute
  '/': typeof AppIndexRoute
  '/anggota/$slug': typeof AppAnggotaSlugRoute
  '/berita/$slug': typeof AppBeritaSlugRoute
  '/news/$slug': typeof AppNewsSlugRoute
  '/people/$slug': typeof AppPeopleSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/anggota': typeof AppAnggotaIndexRoute
  '/berita': typeof AppBeritaIndexRoute
  '/news': typeof AppNewsIndexRoute
  '/people': typeof AppPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/embed': typeof EmbedRoute
  '/embed.js': typeof EmbedDotjsRoute
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/penelitian': typeof AppPenelitianRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/tentang': typeof AppTentangRoute
  '/_app/widget': typeof AppWidgetRoute
  '/api/news': typeof ApiNewsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/anggota/$slug': typeof AppAnggotaSlugRoute
  '/_app/berita/$slug': typeof AppBeritaSlugRoute
  '/_app/news/$slug': typeof AppNewsSlugRoute
  '/_app/people/$slug': typeof AppPeopleSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/anggota/': typeof AppAnggotaIndexRoute
  '/_app/berita/': typeof AppBeritaIndexRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/embed.js'
    | '/login'
    | '/about'
    | '/admin'
    | '/penelitian'
    | '/research'
    | '/tentang'
    | '/widget'
    | '/api/news'
    | '/anggota/$slug'
    | '/berita/$slug'
    | '/news/$slug'
    | '/people/$slug'
    | '/api/auth/$'
    | '/anggota/'
    | '/berita/'
    | '/news/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/embed'
    | '/embed.js'
    | '/login'
    | '/about'
    | '/admin'
    | '/penelitian'
    | '/research'
    | '/tentang'
    | '/widget'
    | '/api/news'
    | '/'
    | '/anggota/$slug'
    | '/berita/$slug'
    | '/news/$slug'
    | '/people/$slug'
    | '/api/auth/$'
    | '/anggota'
    | '/berita'
    | '/news'
    | '/people'
  id:
    | '__root__'
    | '/_app'
    | '/embed'
    | '/embed.js'
    | '/login'
    | '/_app/about'
    | '/_app/admin'
    | '/_app/penelitian'
    | '/_app/research'
    | '/_app/tentang'
    | '/_app/widget'
    | '/api/news'
    | '/_app/'
    | '/_app/anggota/$slug'
    | '/_app/berita/$slug'
    | '/_app/news/$slug'
    | '/_app/people/$slug'
    | '/api/auth/$'
    | '/_app/anggota/'
    | '/_app/berita/'
    | '/_app/news/'
    | '/_app/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  EmbedDotjsRoute: typeof EmbedDotjsRoute
  LoginRoute: typeof LoginRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed.js': {
      id: '/embed.js'
      path: '/embed.js'
      fullPath: '/embed.js'
      preLoaderRoute: typeof EmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/penelitian': {
      id: '/_app/penelitian'
      path: '/penelitian'
      fullPath: '/penelitian'
      preLoaderRoute: typeof AppPenelitianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tentang': {
      id: '/_app/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof AppTentangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/widget': {
      id: '/_app/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof AppWidgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/anggota/': {
      id: '/_app/anggota/'
      path: '/anggota'
      fullPath: '/anggota/'
      preLoaderRoute: typeof AppAnggotaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anggota/$slug': {
      id: '/_app/anggota/$slug'
      path: '/anggota/$slug'
      fullPath: '/anggota/$slug'
      preLoaderRoute: typeof AppAnggotaSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/berita/': {
      id: '/_app/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof AppBeritaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/berita/$slug': {
      id: '/_app/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof AppBeritaSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/$slug': {
      id: '/_app/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof AppNewsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$slug': {
      id: '/_app/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof AppPeopleSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAdminRoute: typeof AppAdminRoute
  AppPenelitianRoute: typeof AppPenelitianRoute
  AppResearchRoute: typeof AppResearchRoute
  AppTentangRoute: typeof AppTentangRoute
  AppWidgetRoute: typeof AppWidgetRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnggotaSlugRoute: typeof AppAnggotaSlugRoute
  AppBeritaSlugRoute: typeof AppBeritaSlugRoute
  AppNewsSlugRoute: typeof AppNewsSlugRoute
  AppPeopleSlugRoute: typeof AppPeopleSlugRoute
  AppAnggotaIndexRoute: typeof AppAnggotaIndexRoute
  AppBeritaIndexRoute: typeof AppBeritaIndexRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAdminRoute: AppAdminRoute,
  AppPenelitianRoute: AppPenelitianRoute,
  AppResearchRoute: AppResearchRoute,
  AppTentangRoute: AppTentangRoute,
  AppWidgetRoute: AppWidgetRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnggotaSlugRoute: AppAnggotaSlugRoute,
  AppBeritaSlugRoute: AppBeritaSlugRoute,
  AppNewsSlugRoute: AppNewsSlugRoute,
  AppPeopleSlugRoute: AppPeopleSlugRoute,
  AppAnggotaIndexRoute: AppAnggotaIndexRoute,
  AppBeritaIndexRoute: AppBeritaIndexRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  EmbedRoute: EmbedRoute,
  EmbedDotjsRoute: EmbedDotjsRoute,
  LoginRoute: LoginRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
